### ISSUE TITLE
[Improvement] Remove BOOST_DI_INJECT_TRAITS and other macros

### ISSUE THREAD

**Issue by mcencora** [boost-ext/di#204]
Allow specifying constructor signature instead of the traits and macros:

```
struct C
{
    C(int, double);
    C(double, int);
};
auto object = injector.create<C(int, double)>();
```

**Comment by kris-jusiak** [comment]
Thanks for the suggestion Maciek!

BOOST_DI_INJECT_TRAITS and other macros are optional and used in following scenarios:
- ambiguity of constructors (your example)
- named/annotation parameters (due to performance, name might be removed)
- generation of constructor traits for third-party libraries

Anyway, moving on to your example. Although, looks simple it won't work very well for more complex cases, such as.

``` cpp
struct B {
    B(int, double);
    B(double, int);
};
struct C {
    C(B, double);
    C(double, B);
};
auto object = injector.create<C(B(int, double), double)>(); // that would be madness in more complex scenarios
```

Nonetheless, they are ways to avoid macros and the boilerplate code in your example.
- Using '...' to select the constructor

``` cpp
struct C {
    C(int, double);
    C(double, int, ...); // a bit intrusive, but it does the job
};
auto object = injector.create<C>();
```

Example here -> https://github.com/krzysztof-jusiak/di/blob/cpp14/example/automatic_injection.cpp
- Using 'to(consructor)' extension to select the constructor

``` cpp
struct C {
    C(int, double);
    C(double, int);
};
auto injector = di::make_injector(
    di::bind<C>.to(constructor<int, double>)
);
auto object = injector.create<C>();
```

Example here -> https://github.com/krzysztof-jusiak/di/blob/cpp14/example/extensions/bindings/constructor_bindings.cpp

Hope that above example explain reasons why such design was used and how to avoid using of macros in your example.
