### ISSUE TITLE
Passing injectors to sub systems?

### ISSUE THREAD

**Issue by judgeaxl** [boost-ext/di#213]
This looks like quite an interesting library. Only one question; Since Injector is a complicated template, typed on the bindings it contains, how would one go about passing a pre-constructed injector to a sub-system which cannot know about all the details of the template? All it must know about is an object Injector with a create<T>() function. I've considered various ways of removing this constraint, but at the moment none of them are very compelling.

```
auto injector = di::make_injector(/* stuffs */);
auto subsystem = injector->create<SubSystem>();
subsystem->configure(injector); // init is not a template function
```

I've been digging through all of the popular C++ DI libraries, and most support this particular feature, but lack others, with this one coming closest overall to what I want, if I can only solve this problem in a satisfactory way.

**Comment by kris-jusiak** [comment]
Thanks for the question, I would really like to see your problem though because I have never seen design which would definitely need such solution but I might be wrong. Nevertheless, what you asking for might be achieved with boost.di via exposing injector types (which, basically is just a type erasure leaving injector with create methods for specific types). So, in your case the code will look more or less like that.

```
class SubSystem {
  ...
  void configure(di::injector<...>); // where ... are types to be exposed
};

auto injector = di::make_injector(...);
auto subsystem = injector.create<SubSystem>();
subsystem.configure(std::move(injector));
```

You can find full example here -> http://melpon.org/wandbox/permlink/i0bjHLFm2LOexTgr
More info about exposed types here -> http://boost-experimental.github.io/di/user_guide/index.html#BOOST_DI_EXPOSE

Hope that this helps a bit.

**Comment by judgeaxl** [comment]
Thanks! If it's enough to specify the possible products as the types in the template, that should be reasonable, and I can easily create a typedef for that.

So, my problem is that I've got a set of global services that I need to inject in various sub systems, sort of the default scenario with DI. But each sub system may need to construct further objects, models, over time, and they themselves need the ability to create certain sibling objects. Each of which may require injection of the global services, or the sub system instances themselves. In addition, all the model objects need to be serializable, so I have multiple systems that can create models, that are essentially independent.

Some of this could be resolved by creating more regular factory functions inside the sub systems, which could hold on to the originally injected dependencies, and pass them on to whatever they create, but I'm looking for ways to avoid having more than one system that does similar things.

**Comment by kris-jusiak** [comment]
Yea, your problem seems to be quite complex. Most likely, it would be really hard to find a good solution without a huge refactoring or redesign.
It's always really hard to add support for DI if the app wasn't designed to support it from the beginning. I guess, that's a flaw of DI in general, but I also doubt that much can be done about it. I'm really happy though, that you have found a way to solve your issue. Thanks for the explanation.
