### ISSUE TITLE
Broken under VS2015 Update 3

### ISSUE THREAD

**Issue by alongubkin** [boost-ext/di#219]
The following code doesn't compile under VS2015 Update 3:

```
struct A {
    virtual void x() = 0;
}

struct B : public A {
    virtual void x() override {}
}

auto injector = di::make_injector(
    di::bind<A>().to<B>()
);

injector.create<A>();
```

Note that without the method `x`, it works. It also works when calling `injector.create<B>()` instead.

The error is something like "no matching overload function found".

**Comment by kris-jusiak** [comment]
@alongubkin thanks for reporting it, I'm taking a look as we speak.
- Clang-3.9 - optimization issue causing asm opcodes comparison tests to fail
- GCC-6 - can access private aliases causing some compile tests to fail
- MSVC-2015-3 - doesn't compile :/

Nice ;)

**Comment by kris-jusiak** [comment]
I took a look and it seems that you are trying to instantiate a pure interface, which won't work. Unfortunately, DI error is not as good, so I created a task to fix the error message. You can track the progress here -> https://github.com/boost-experimental/di/issues/220.

Anyway, moving back to your example. The proper use of A will require usage of a pointer of some sort.

``` cpp
struct A {
    virtual ~A() = default;
    virtual void x() = 0;
};

struct B : public A {
    void x() override {}
};

int main() {
  auto injector = di::make_injector(
    di::bind<A>().to<B>()
  );

  auto object = injector.create<B>();  //okay
  auto object = injector.create<std::unique_ptr<A>>();  //okay
  auto object = injector.create<std::shared_ptr<A>>();  //okay
  std::unique_ptr<A> a{injector.create<A*>()};  //okay
//  auto object = injector.create<A>();  // can't work, same as A a;
}
```

The proper error message should look like the one when trying to create `A` on stack.

``` cpp
int main() {
  A a;
}

--- output ---

main.cpp(3004): error C2259: 'A': cannot instantiate abstract class
main.cpp(3004): note: due to following members:
main.cpp(3004): note: 'void A::x(void)': is abstract
main.cpp(2988): note: see declaration of 'A::x'
```

**Comment by alongubkin** [comment]
Actually sorry, you are right, the code I presented in the original issue was completely irrelevant. The issue is with the following code:

```
struct A {};

struct B {
    explicit B(A&) {}
    B(const B&) = delete;
};

struct C {
    explicit C(B&) {}
};
```

I checked with both VS2015 Update 2 and VS2015 Update 3. In Update 2, this code compiles successfully, but in Update 3 it throws "creatable constraint not satisfied".

If I add a copy constructor to B, it works, but it's extremely problematic to do that in my codebase.

Any ideas?

**Comment by alongubkin** [comment]
Hi, any updates on this?

**Comment by kris-jusiak** [comment]
Hi @alongubkin. Thanks for the example. So the problem is that, deleted functions still participate in the overload resolution and therefore your example doesn't work. Honestly, IMHO, Update 2 worked only because MSVC had some issue with handling it properly. Anyway, this issue is a bug and I will try to fix it ASAP.

For know, I can only give you some workarounds to deal with it.
- The problem occurs only when constructor has one argument, so an easy fix would be to add more constructor parameters

``` cpp
struct B {
    explicit B(A&, ...) {} /// NOTICE ..., any other parameter will work too, but it would change the ctor requirements
    B(const B&) = delete;
};
```
- If you can make B movable

``` cpp
struct B {
    explicit B(A&) {}
    B(B&) = default;
    B(const B&) = delete;
};
```
- you can also say explicitly what parameters should be used by the constructor

``` cpp
struct B {
    BOOST_DI_INJECT(explicit B, A&) {}
    B(const B&) = delete;
};
```

Please also notice that

``` cpp
injector.create<B>();
```

can't work as B has to be copyable in that case

**Comment by alongubkin** [comment]
Thank you, the `...` workaround is working great.

**Comment by kris-jusiak** [comment]
I hope you don't mind @alongubkin that I have reopened this issue as I would like to provide a proper fix for it. Issue should be fixed on clang and gcc by https://github.com/boost-experimental/di/commit/a809130c23bb1996d1a9a8bd8c9fbc3e75e01a82. However, I'm not sure about msvc yet because http://webcompiler.cloudapp.net/ is in maintenance. Hopefully, appveyor will give us a positive test results too.

If you have any other cases different than in the test cases I have added in https://github.com/boost-experimental/di/commit/a809130c23bb1996d1a9a8bd8c9fbc3e75e01a82 and which may cause problem or should be supported, I would really appreciate if you could share them here. Thanks.

**Comment by kris-jusiak** [comment]
It seems to be working properly now in MSVC 2015 too - https://ci.appveyor.com/project/krzysztof-jusiak/di/build/1.0.176.

**Comment by alongubkin** [comment]
Working for me too in Update 3. Thank you!
