### ISSUE TITLE
Exception in ctor not propagated

### ISSUE THREAD

**Issue by Brunni** [boost-ext/di#227]
Hi,

I really like having DI in my code it makes it very readable and testable!

My Problem:
If my configuration settings are wrong, the constructor throws an exception stating which value is missing. This exception is swalloed and the program terminates with errorcode 3.

Example ctor
```
cerr << "Starting ctor" << endl;
config->getEntry("threshold"); // this throws exception
cerr << "ctor finished" << endl;
```

Result on console: I see the first message and then program terminates.

System:
- Execution with GTest framework.
- Windows, Visual Studio 2015.3

**Comment by klemen-forstneric** [comment]
I think this happens due to the fact that injector's `create` method marked as `noexcept`. When instantiating a dependency throws, the exception isn't caught inside the `create`, thus terminating the application, because the `noexcept` 'contract' is breached.

I'm wondering though, about the rationale of making it noexcept?
