### ISSUE TITLE
How to inject a same dependency instance as shared_ptr and raw pointer ? 

### ISSUE THREAD

**Issue by LempereurBenjamin** [boost-ext/di#331]
For example, I have a class B inherited from an abstract class A.
I want to inject the B class as a shared_ptr of A in another class and the same instance as a raw pointer.

Sample code of the injector :
```
auto injector = boost::di::make_injector
(
    boost::di::bind<A>.to<B>().in(boost::di::singleton)
    //,boost::di::bind<A>.to<B>().in(boost::di::unique) Which one? Both?
);
    
C c = injector.create<C>();
D d = injector.create<D>();
```

![sowkiimgastdushcaqajiajcjblmve9apaaibbpmuk9olb2fqkl9by_j0_awmiuarlmapxh59ibmlikpykmfav459kkszdqqnblw7rf5cuap9reapz0tby0tbxgema0lo0kvgmb0uhskxziy5a3b0000](https://user-images.githubusercontent.com/6420842/39360578-287be8a2-4a1f-11e8-88dc-5da3699dbb24.png)
How can I do this with Boost.DI ?

**Comment by kris-jusiak** [comment]
Thanks @LempereurBenjamin. DI will take care of the conversions for you, however, shared wrapper (default for shraed objects) is not convertible to a pointer at the moment to avoid confusion with a raw pointer from a unique scope (if only have a nice owned pointer in C++).

Try reference instead of pointer, the following should work:
```cpp
C(std::shared_ptr<A>);
D(A&);
```

**Comment by LempereurBenjamin** [comment]
@krzysztof-jusiak Thank you for your answer.
