### ISSUE TITLE
Different injectors create same singleton shared_ptr

### ISSUE THREAD

**Issue by Warchant** [boost-ext/di#431]
## Expected Behavior
Different injectors should create different singletons (`std::shared_ptr`).

## Actual Behavior
Different injectors create same singleton (`std::shared_ptr`).

## Steps to Reproduce the Problem

https://godbolt.org/z/qVF9TI

In this example, `Impl` should have been created 2 times, because we use 2 different injectors.

## Specifications

  - Version: 4767207694ceba58b7655805193249d54e3bf405
  - Platform: Mac

**Comment by Warchant** [comment]
@krzysztof-jusiak

**Comment by kris-jusiak** [comment]
Thanks, @Warchant for your bug report and the example :+1: 

By default (due to performance reasons) a singleton (global per app scope) is used.

In order to get `shared` per `injector` scope a `shared` scope has to be used:
```
        boost::di::bind<Interface>.to<Impl>().in(boost::di::extension::shared) // shared per injector
```

Full example here -> https://wandbox.org/permlink/4D4GXnqyPGijJb5X

More information might be found:
* https://boost-experimental.github.io/di/user_guide/index.html#scopes
* Tutorial - [Basic] Decide the life times
* https://boost-experimental.github.io/di/extensions/index.html#shared-scope

Please also notice that you **can also change the default behaviour** (for shared scope to be a default one) by
```
    auto injector = di::make_injector<di::extension::shared_config>(...);
```

Example here -> https://wandbox.org/permlink/4D4GXnqyPGijJb5X

I hope that makes sense.
