### ISSUE TITLE
[Question] Difference between scoped scope and shared scope.

### ISSUE THREAD

**Issue by FranckRJ** [boost-ext/di#475]
Hello, I've tried to find more information about scoped scope and shared scope but I don't understand what's the difference between the two (didn't find any doc about it, and I don't understand the difference by reading the examples).

By reading the source code it looks like shared scope can be thread safe, and it provide a config to make it the default scope for an injector, but beside that i don't know.

Can you help me ? Thanks !

**Comment by kris-jusiak** [comment]
Hi @FranckRJ,

There is no that much difference between them
* Both of them are extensions and might be used instead of a default singleton scope to couple the lifetime of objects to the injector
* Both of them will be much slower than the default `singleton` scope
* `shared` scope is `thread` safe by default whilst `scoped` is not at all
* `shared` scope can also be defaulted instead of `singleton` scope via `shared_config`

Thanks, Kris

**Comment by FranckRJ** [comment]
Ok, i see better now, thanks !
